portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('src.urls'))
]

src/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='home')
]

src/models.py
from django.contrib.auth.models import User
from django.db import models


class Project(models.Model):
    project_title = models.CharField(max_length=100)
    project_description = models.TextField()
    languages_used = models.CharField(max_length=100)
    github_repo = models.CharField(max_length=100)

    def __str__(self):
        return self.project_title

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    about = models.TextField()
    my_resume = models.FileField(blank=True, null=True)
    instagram = models.CharField(max_length=100)
    github = models.CharField(max_length=100)
    linkedin = models.CharField(max_length=100)
    gmail = models.CharField(max_length=100)
    twitter = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

src/views.py
from django.shortcuts import render

from .models import Profile, Project

# Create your views here.


def index(request):
    projects = Project.objects.all()
    profile = Profile.objects.get(pk=1)
    context = {'all_projects': projects, 'profile': profile}
    return render(request, 'index.html', context)

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Welcome | imshalem</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">


</head>

<body>
    <section class="s1">
        <div class="main-container">
            <div class="nav-wrapper">
                <div class="brand">
                    <a class="brand-name" href="{% url 'main:home' %}">im<span><b>shalem</b></span></a>
                </div>
                <ul id="navigation">
                    <li><a href="#contact-wrapper">about</a></li>
                    <li><a href="#social">projects</a></li>
                    <li><a href="#contact-wrapper">contact</a></li>
                </ul>
            </div>
        </div>  
    </section>

    <section class="s2">
        
        <div class="center-column">
            <div class="intro">
                <img id="profile-pic" src="{% static 'images/animoji.png' %}">
                <h1 class="intro-text">Hi, I'm Shalem !</h1>
                <p class="short-about">I'm a Web Developer/Machine Learning  <br>
                    Specialist with Applied Modelling Team at Amazon</p>

                <div class="link-block">
                    <ul id="about-nav">
                        <li><a href="#social">projects</a></li>
                        <li><a target="_blank" href="https://www.linkedin.com/in/shalem-singh-rajput-5b4843140/">linkedin</a></li>
                    </ul>   
                </div>
            </div>
        </div>

        
    </section>

    <section class="s4">
        <div class="social-link-wrapper">
            <div class="social-links">
                <ul id="social">
                    <li><a target="_blank" class="fa fa-github" href="{{ profile.github }}"></a></li>
                    <li><a target="_blank" class="fa fa-instagram" href="{{ profile.instagram }}"></a></li>
                    <li><a target="_blank" class="fa fa-google" href="#"></a></li>

                </ul>
            </div>
        </div>
    </section>

    <section class="s3">
        <div class="main-container">
            <div class="project-wrapper">
                <div class="work-heading">
                    <p>Some of my works</p>
                </div>

                <div class="projects">
                    {% for project in all_projects %}
                        <a target="_blank" href="{{ project.github_repo }}"><div class="work">
                        <div class="work-preview">
                            <h4 class="project-title">{{ project.project_title }}</h4>
                            <p class="project-intro">{{ project.project_description }}</p>
                            <p class="language">{{ project.languages_used }}</p>
                        </div></a>
                    </div>
                    {% endfor %}
                </div>

        </div>

    </section>

    <section class="s5">
        <div class="main-container">
            <div id="contact-wrapper">
                <div class="contact-heading">
                    <p>About</p>
                </div>

                <div class="contact-info">
                    <p>I am a self-taught Django developer with a bachelors
                        degree, specializing in Backend Development.<br>
                        I have always found coding intuitive and have pushed
                        myself to learn and pursue it as a career. As someone
                        who enjoys finding solutions to difficult problems,
                        transforming ideas into reality, web development was
                        an obvious path.<br>
                        I'm a fast learner and can quickly integrate into a team
                        providing value to the company & the customer with
                        the knowledge I have.</p>
                    
                </div>
            </div>

        </div>

    </section>

    <section class="s5">
        <div class="main-container">
            <div id="contact-wrapper">
                <div class="contact-heading">
                    <p style="font-size: 15px;">Mail me at <b>shalem000@gmail.com</b></p>
                </div>
            </div>

        </div>

    </section>


</body>
</html>